### ISSUE TITLE
Request: arm64 image(s)

### ISSUE THREAD

**Issue by danielluke** [cloudnative-pg/pgbouncer-containers#12]
Would love to have linux/arm64 versions (for local testing on rpi cluster).

**Comment by sxd** [comment]
@danielluke the images are in the pgbouncer-testing, if you can test it will be great!

**Comment by danielluke** [comment]
Tried with:
```
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: example-rw
  namespace: example
spec:
  cluster:
    name: exampledb

  instances: 2
  type: rw

  pgbouncer:
    poolMode: transaction

  template:
    spec:
      containers:
      - name: pooler
        image: ghcr.io/cloudnative-pg/pgbouncer-testing:main
```
... images crash loop with:

```
2022-06-21 21:43:04.499 UTC [8] ERROR load_init_file: main section missing from config file
2022-06-21 21:43:04.500 UTC [8] FATAL cannot load config file
```
 
I haven't had a chance to do any debugging (yet).
