### ISSUE TITLE
bouncer config error

### ISSUE THREAD

**Issue by kokorousaki** [cloudnative-pg/pgbouncer-containers#54]
env:
operator: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.5
postgres: ghcr.io/cloudnative-pg/postgresql:15.10
pooler: ghcr.io/cloudnative-pg/pgbouncer:1.24.0

I use pgsql to connect to the pooler’s service (svc), but some databases report an error (bouncer config error), while others work fine. What could be the reason?
```bash
pgctl:/# psql -h xxx -U postgres -d bussiness
psql: error: connection to server at "xxx" (10.242.218.167), port 5432 failed: FATAL:  bouncer config error
connection to server at "xxx" (10.242.218.167), port 5432 failed: FATAL:  bouncer config error
```
<img width="1853" alt="Image" src="https://github.com/user-attachments/assets/17918a96-f2b2-4088-aae4-0254d6f80e61" />
I’ve tried many versions of the pooler, but the same error persists.

Here is my pooler template:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-xxx-postgres-rw
  namespace: postgres
spec:
  cluster:
    name: xxx-postgres
  type: rw
  instances: 1
  template:
    spec:
      containers:
        - name: pgbouncer
          image: ghcr.io/cloudnative-pg/pgbouncer:1.24.0
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 4Gi
  pgbouncer:
    poolMode: session
    parameters:
      default_pool_size: "10"
      max_client_conn: "1000"
      verbose: "3"
    pg_hba:
      - local all all peer map=local
      - host all all all scram-sha-256
```
